package com.lovecube.backend.growth.enums;

public enum GrowthEventType {
    USER_REGISTERED,
    USER_PROFILE_COMPLETED,
    USER_DAILY_ACTIVE,
    POST_CREATED,
    POST_LIKED,
    POST_COMMENTED,
    GROUP_CREATED,
    GROUP_JOINED,
    USER_INVITED_REGISTERED,
    USER_INVITED_EFFECTIVE,
    PROFILE_AVATAR_SET,
    PROFILE_AGE_SET,
    PROFILE_CITY_SET,
    PROFILE_BIO_SET,
    PROFILE_PHOTOS_UPLOADED,
    PROFILE_VERIFIED,
    FELLOWSHIP_ENABLED
}
