#!/usr/bin/env bash
# 把 GitHub Secrets / 当前环境变量合并进服务器 env 文件。
# 规则：incoming 非空则覆盖；incoming 为空则保留已有值。禁止用空 Secret 冲掉线上关键变量。
set -euo pipefail

ENV_FILE="${1:-/opt/lovecube-api/lovecube-api.env}"
TMP_FILE="$(mktemp)"
trap 'rm -f "$TMP_FILE"' EXIT

umask 077

declare -A OLD=()
if [ -f "$ENV_FILE" ]; then
  while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in
      ''|\#*) continue ;;
    esac
    key="${line%%=*}"
    value="${line#*=}"
    if [ -n "$key" ] && [ "$key" != "$line" ]; then
      OLD["$key"]="$value"
    fi
  done < "$ENV_FILE"
fi

incoming() {
  local key="$1"
  printf '%s' "${!key-}"
}

pick() {
  local key="$1"
  local from_env
  from_env="$(incoming "$key")"
  if [ -n "$from_env" ]; then
    printf '%s' "$from_env"
    return
  fi
  printf '%s' "${OLD[$key]:-}"
}

SPRING_PROFILES_ACTIVE_VAL="$(pick SPRING_PROFILES_ACTIVE)"
if [ -z "$SPRING_PROFILES_ACTIVE_VAL" ]; then
  SPRING_PROFILES_ACTIVE_VAL="prod"
fi

SPRING_DATASOURCE_URL_VAL="$(pick SPRING_DATASOURCE_URL)"
SPRING_DATASOURCE_USERNAME_VAL="$(pick SPRING_DATASOURCE_USERNAME)"
if [ -z "$SPRING_DATASOURCE_USERNAME_VAL" ]; then
  SPRING_DATASOURCE_USERNAME_VAL="$(pick DB_USERNAME)"
fi
SPRING_DATASOURCE_PASSWORD_VAL="$(pick SPRING_DATASOURCE_PASSWORD)"
if [ -z "$SPRING_DATASOURCE_PASSWORD_VAL" ]; then
  SPRING_DATASOURCE_PASSWORD_VAL="$(pick DB_PASSWORD)"
fi
JWT_SECRET_VAL="$(pick JWT_SECRET)"

missing=()
[ -n "$SPRING_DATASOURCE_URL_VAL" ] || missing+=("SPRING_DATASOURCE_URL")
[ -n "$SPRING_DATASOURCE_USERNAME_VAL" ] || missing+=("SPRING_DATASOURCE_USERNAME")
[ -n "$SPRING_DATASOURCE_PASSWORD_VAL" ] || missing+=("SPRING_DATASOURCE_PASSWORD")
[ -n "$JWT_SECRET_VAL" ] || missing+=("JWT_SECRET")
if [ "${#missing[@]}" -gt 0 ]; then
  echo "[write-env] ERROR: 合并后仍缺少必填项: ${missing[*]}" >&2
  echo "[write-env] 请在 GitHub Secrets 填写，或先保留服务器上已有的 lovecube-api.env" >&2
  exit 1
fi

OSS_ENABLED_VAL="$(pick OSS_ENABLED)"
if [ -z "$OSS_ENABLED_VAL" ]; then
  OSS_ENABLED_VAL="true"
fi

NOTIFICATION_MAIL_ENABLED_VAL="$(pick NOTIFICATION_MAIL_ENABLED)"
if [ -z "$NOTIFICATION_MAIL_ENABLED_VAL" ]; then
  NOTIFICATION_MAIL_ENABLED_VAL="false"
fi

write_kv() {
  printf '%s=%s\n' "$1" "$2"
}

# systemd EnvironmentFile 里 KEY= 会变成空字符串，并覆盖 YAML 默认值。
# 布尔/数字空值会让 Spring 启动失败，因此空的可选变量直接不写。
write_optional() {
  local key="$1"
  local value="$2"
  if [ -n "$value" ]; then
    write_kv "$key" "$value"
  fi
}

{
  echo "# generated by deploy/write-env.sh — do not commit real values"
  write_kv SPRING_PROFILES_ACTIVE "$SPRING_PROFILES_ACTIVE_VAL"
  write_kv SPRING_DATASOURCE_URL "$SPRING_DATASOURCE_URL_VAL"
  write_kv SPRING_DATASOURCE_USERNAME "$SPRING_DATASOURCE_USERNAME_VAL"
  write_kv SPRING_DATASOURCE_PASSWORD "$SPRING_DATASOURCE_PASSWORD_VAL"
  write_kv JWT_SECRET "$JWT_SECRET_VAL"
  write_optional APP_BASE_URL "$(pick APP_BASE_URL)"
  write_optional WECHAT_APPID "$(pick WECHAT_APPID)"
  write_optional WECHAT_SECRET "$(pick WECHAT_SECRET)"
  write_kv OSS_ENABLED "$OSS_ENABLED_VAL"
  write_optional OSS_ACCESS_KEY_ID "$(pick OSS_ACCESS_KEY_ID)"
  write_optional OSS_ACCESS_KEY_SECRET "$(pick OSS_ACCESS_KEY_SECRET)"
  write_optional OSS_ENDPOINT "$(pick OSS_ENDPOINT)"
  write_optional OSS_BUCKET_NAME "$(pick OSS_BUCKET_NAME)"
  write_optional OSS_CDN_DOMAIN "$(pick OSS_CDN_DOMAIN)"
  write_optional MAIL_HOST "$(pick MAIL_HOST)"
  write_optional MAIL_PORT "$(pick MAIL_PORT)"
  write_optional MAIL_USERNAME "$(pick MAIL_USERNAME)"
  write_optional MAIL_PASSWORD "$(pick MAIL_PASSWORD)"
  write_kv NOTIFICATION_MAIL_ENABLED "$NOTIFICATION_MAIL_ENABLED_VAL"
} > "$TMP_FILE"

MANAGED=" SPRING_PROFILES_ACTIVE SPRING_DATASOURCE_URL SPRING_DATASOURCE_USERNAME SPRING_DATASOURCE_PASSWORD JWT_SECRET APP_BASE_URL WECHAT_APPID WECHAT_SECRET OSS_ENABLED OSS_ACCESS_KEY_ID OSS_ACCESS_KEY_SECRET OSS_ENDPOINT OSS_BUCKET_NAME OSS_CDN_DOMAIN MAIL_HOST MAIL_PORT MAIL_USERNAME MAIL_PASSWORD NOTIFICATION_MAIL_ENABLED "
if [ "${#OLD[@]}" -gt 0 ]; then
  for key in "${!OLD[@]}"; do
    case "$MANAGED" in
      *" $key "*) continue ;;
    esac
    write_optional "$key" "${OLD[$key]}" >> "$TMP_FILE"
  done
fi

mkdir -p "$(dirname "$ENV_FILE")"
if [ -f "$ENV_FILE" ]; then
  cp -a "$ENV_FILE" "${ENV_FILE}.bak.$(date +%Y%m%d-%H%M%S)"
fi
mv "$TMP_FILE" "$ENV_FILE"
chmod 600 "$ENV_FILE"
trap - EXIT
echo "[write-env] wrote $ENV_FILE (required keys present; empty incoming values did not wipe existing ones)"
