import authRoutes from './auth.routes.js'

export default {
  path: '/',
  component: () => import('@/layouts/PlatformLayout.vue'),
  children: [
    ...authRoutes,
    { path: '', component: () => import('@/pages/WebsiteHome.vue'), meta: { module: 'platform' } },
    { path: 'platform', component: () => import('@/pages/platform/HomePage.vue'), meta: { module: 'platform' } },
    { path: 'platform/local', component: () => import('@/pages/platform/LocalResourcesPage.vue'), meta: { module: 'platform' } },
    { path: 'platform/content', component: () => import('@/pages/platform/PlatformContentPage.vue'), meta: { module: 'platform' } },
    { path: 'platform/publish', component: () => import('@/pages/platform/PlatformPublishPage.vue'), meta: { module: 'platform', requiresAuth: true } },
    { path: 'platform/checkin', component: () => import('@/pages/platform/CheckinPage.vue'), meta: { module: 'platform', requiresAuth: true } },
    { path: 'me', redirect: '/platform/me', meta: { module: 'platform' } },
    { path: 'platform/me', component: () => import('@/pages/platform/MePage.vue'), meta: { module: 'platform', requiresAuth: true } },
    { path: 'me/profile', component: () => import('@/pages/platform/MyProfilePage.vue'), meta: { module: 'platform', requiresAuth: true } },
    { path: 'me/posts', component: () => import('@/pages/platform/MyPostsPage.vue'), meta: { module: 'platform', requiresAuth: true } },
    { path: 'me/favorites', component: () => import('@/pages/platform/MyFavoritesPage.vue'), meta: { module: 'platform', requiresAuth: true } },
    { path: 'me/drafts', component: () => import('@/pages/platform/MyDraftsPage.vue'), meta: { module: 'platform', requiresAuth: true } },
    { path: 'me/tasks', component: () => import('@/pages/platform/MyTasksPage.vue'), meta: { module: 'platform', requiresAuth: true } },
    { path: 'me/badges', component: () => import('@/pages/platform/MyBadgesPage.vue'), meta: { module: 'platform', requiresAuth: true } },
    { path: 'me/security', component: () => import('@/pages/platform/MySecurityPage.vue'), meta: { module: 'platform', requiresAuth: true } },
    { path: 'me/feedback', component: () => import('@/pages/platform/MyFeedbackPage.vue'), meta: { module: 'platform', requiresAuth: true } },
    { path: 'me/verify', component: () => import('@/pages/platform/MyVerifyPage.vue'), meta: { module: 'platform', requiresAuth: true } },
    { path: 'me/privacy', component: () => import('@/pages/platform/MyPrivacyPage.vue'), meta: { module: 'platform', requiresAuth: true } },
    { path: 'me/notifications', component: () => import('@/pages/platform/MyNotificationsPage.vue'), meta: { module: 'platform', requiresAuth: true } },
    { path: 'me/groups', redirect: '/platform/me/groups', meta: { module: 'platform' } },
    { path: 'account', redirect: '/me', meta: { module: 'platform' } },
    { path: 'messages', component: () => import('@/pages/platform/MessagesCenterPage.vue'), meta: { module: 'platform', requiresAuth: true } },
    { path: 'announcements', component: () => import('@/pages/platform/AnnouncementsPage.vue'), meta: { module: 'platform' } },
    { path: 'announcements/:id', component: () => import('@/pages/platform/AnnouncementDetailPage.vue'), meta: { module: 'platform' } },
    { path: 'platform/changelog', component: () => import('@/pages/platform/HomeChangelogPage.vue'), meta: { module: 'platform' } },
    { path: 'platform/pending-updates', component: () => import('@/pages/platform/HomePendingUpdatesPage.vue'), meta: { module: 'platform' } },
    { path: 'articles', redirect: '/platform/articles', meta: { module: 'platform' } },
    { path: 'platform/articles', component: () => import('@/pages/platform/ArticlesPage.vue'), meta: { module: 'platform' } },
    { path: 'articles/:id', component: () => import('@/pages/platform/ArticleDetailPage.vue'), meta: { module: 'platform' } },
    { path: 'events', redirect: '/platform/events', meta: { module: 'platform' } },
    { path: 'platform/events', component: () => import('@/pages/platform/EventsPage.vue'), meta: { module: 'platform' } },
    { path: 'events/:id', component: () => import('@/pages/platform/EventDetailPage.vue'), meta: { module: 'platform' } },
    { path: 'about', redirect: '/feedback', meta: { module: 'platform' } },
    { path: 'fellowship-intro', component: () => import('@/pages/platform/FellowshipIntroPage.vue'), meta: { module: 'platform' } },
    { path: 'modules', component: () => import('@/pages/platform/ModulesPage.vue'), meta: { module: 'platform' } },
    { path: 'platform/positive-share', component: () => import('@/pages/platform/PositiveSharePage.vue'), meta: { module: 'platform' } },
    { path: 'platform/help', component: () => import('@/pages/platform/HelpSquarePage.vue'), meta: { module: 'platform' } },
    { path: 'platform/help/create', component: () => import('@/pages/platform/HelpCreatePage.vue'), meta: { module: 'platform', requiresAuth: true } },
    { path: 'platform/help/my', component: () => import('@/pages/platform/HelpMyPage.vue'), meta: { module: 'platform', requiresAuth: true } },
    { path: 'platform/help/:id', component: () => import('@/pages/platform/HelpDetailPage.vue'), meta: { module: 'platform' } },
    { path: 'policies/:id', component: () => import('@/pages/platform/PolicyPage.vue'), meta: { module: 'platform' } },
    { path: 'platform/groups', component: () => import('@/pages/platform/GroupsPage.vue'), meta: { module: 'platform' } },
    { path: 'platform/groups/create', component: () => import('@/pages/platform/GroupCreatePage.vue'), meta: { module: 'platform', requiresAuth: true } },
    { path: 'platform/me/groups', component: () => import('@/pages/platform/MyGroupsPage.vue'), meta: { module: 'platform', requiresAuth: true } },
    { path: 'platform/groups/my', redirect: '/platform/me/groups', meta: { module: 'platform' } },
    { path: 'platform/groups/:id', component: () => import('@/pages/platform/GroupDetailPage.vue'), meta: { module: 'platform' } },
    { path: 'platform/groups/:id/feed', redirect: to => `/platform/groups/${to.params.id}/posts` },
    { path: 'platform/groups/:id/members', component: () => import('@/pages/platform/GroupDetailPage.vue'), meta: { module: 'platform' } },
    { path: 'platform/groups/:id/posts', component: () => import('@/pages/platform/GroupDetailPage.vue'), meta: { module: 'platform' } },
    { path: 'platform/groups/:id/notices', component: () => import('@/pages/platform/GroupDetailPage.vue'), meta: { module: 'platform' } },
    { path: 'platform/groups/:id/profile', component: () => import('@/pages/platform/GroupDetailPage.vue'), meta: { module: 'platform' } },
    { path: 'platform/groups/:id/checkin', component: () => import('@/pages/platform/GroupDetailPage.vue'), meta: { module: 'platform' } },
    { path: 'platform/groups/:id/tasks', component: () => import('@/pages/platform/GroupDetailPage.vue'), meta: { module: 'platform' } },
    { path: 'platform/groups/:id/activities', component: () => import('@/pages/platform/GroupDetailPage.vue'), meta: { module: 'platform' } },
    { path: 'platform/groups/:id/announcements', redirect: to => `/platform/groups/${to.params.id}/notices` },
    { path: 'platform/groups/:id/materials', redirect: to => `/platform/groups/${to.params.id}/profile` }
  ]
}
